### ISSUE TITLE
Port privacy and terms of service pages

### ISSUE THREAD

**Issue by will-weiss** [morehumaninternet/frontend#106]
## Todo

- [ ] Create /pages/roar/privacy.tsx 
- [ ] Create /pages/roar/tos.tsx
- [ ] Each page should use the common Layout component and use the v2 footer. We'll likely need to move those footer styles outside of the `.layout.roar` block so that they can apply in other layouts
- [ ] The header should just be the roar logo, with no other links
- [ ] The background is a solid white background
